export const EMPLOYEE = {
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  GET_EMPLOYEE_BY_ID: 'GET_EMPLOYEE_BY_ID',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  SEARCH_EMPLOYEE: 'SEARCH_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
  EXPORT_EMPLOYEES_EXCEL: 'EXPORT_EMPLOYEES_EXCEL'
};

export const PROVINCE = {
  GET_PROVINCES: 'GET_PROVINCES',
  GET_PROVINCE: 'GET_PROVINCE_BY_ID',
  GET_DISTRICTS: 'GET_DISTRICTS_BY_PROVINCE_ID',
  CREATE_PROVINCE: 'CREATE_PROVINCE',
  UPDATE_PROVINCE: 'UPDATE_PROVINCE',
  SEARCH_PROVINCE: 'SEARCH_PROVINCE',
  DELETE_PROVINCE: 'DELETE_PROVINCE'
}

export const DISTRICT = {
  GET_DISTRICTS: 'GET_DISTRICTS',
  GET_DISTRICT: 'GET_DISTRICT_BY_ID',
  GET_WARDS: 'GET_WARDS_BY_DISTRICT_ID',
  CREATE_DISTRICT: 'CREATE_DISTRICT',
  UPDATE_DISTRICT: 'UPDATE_DISTRICT',
  SEARCH_DISTRICT: 'SEARCH_DISTRICT',
  DELETE_DISTRICT: 'DELETE_DISTRICT'
}

export const WARD = {
  GET_WARDS: 'GET_WARDS',
  GET_WARD: 'GET_WARD_BY_ID',
  CREATE_WARD: 'CREATE_WARD',
  UPDATE_WARD: 'UPDATE_WARD',
  SEARCH_WARD: 'SEARCH_WARD',
  DELETE_WARD: 'DELETE_WARD'
}