export const EMPLOYEE = {
  GET_EMPLOYEES: 'GET_EMPLOYEES',
  GET_EMPLOYEE_BY_ID: 'GET_EMPLOYEE_BY_ID',
  CREATE_EMPLOYEE: 'CREATE_EMPLOYEE',
  UPDATE_EMPLOYEE: 'UPDATE_EMPLOYEE',
  SEARCH_EMPLOYEE: 'SEARCH_EMPLOYEE',
  DELETE_EMPLOYEE: 'DELETE_EMPLOYEE'
};

export const CERTIFICATE = {
  GET_CERTIFICATES: 'GET_CERTIFICATE_BY_ID_EMPLOYEE',
  GET_CERTIFICATE_BY_ID: 'GET_CERTIFICATE_BY_ID',
  CREATE_CERTIFICATE: 'CREATE_CERTIFICATE',
  UPDATE_CERTIFICATE: 'UPDATE_CERTIFICATE',
  DELETE_CERTIFICATE: 'DELETE_CERTIFICATE'
};

export const FAMILY = {
  GET_FAMILY: 'GET_FAMILY_BY_ID_EMPLOYEE',
  GET_FAMILY_BY_ID: 'GET_FAMILY_BY_ID',
  CREATE_FAMILY_MEMBER: 'CREATE_FAMILY_MEMBER',
  UPDATE_FAMILY: 'UPDATE_FAMILY',
  DELETE_FAMILY_MEMBER: 'DELETE_FAMILY_MEMBER'
};